[server]
host = "127.0.0.1"
port = 8080
workers = 4
shutdown_timeout = 30

#[cors]
#allowed_origin = "*"
#allowed_methods = ["GET", "POST"]
#allowed_headers = ["Content-Type", "Authorization"]
#supports_credentials = false
#max_age = 3600
